package view.SubastaProductos;

import java.util.List;
import models.Producto;
import services.ProductoServices;

/**
 *
 * @author YazminG, ErikaC
 */
public class JPanelProductsSubastados extends javax.swing.JPanel {
    
    public JPanelProductsSubastados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnProductosSubast = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnProductosNoSubast = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        btnProductosSubast.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnProductosSubast.setText("Consultar productos subastados");
        btnProductosSubast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosSubastActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Valor inicial", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        btnProductosNoSubast.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnProductosNoSubast.setText("Consultar productos sin subastar");
        btnProductosNoSubast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosNoSubastActionPerformed(evt);
            }
        });

        jTable4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Valor inicial", "Estado"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel1.setText("Consultar productos ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProductosNoSubast)
                            .addComponent(btnProductosSubast))
                        .addGap(51, 51, 51))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(190, 190, 190))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnProductosSubast, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductosNoSubast, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductosSubastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosSubastActionPerformed
        ProductoServices objProductoServices = new ProductoServices();
        List<Producto> lstProductos = objProductoServices.ListarProductos("Subastado");
        cargar_tabla2(lstProductos);
    }//GEN-LAST:event_btnProductosSubastActionPerformed

    private void btnProductosNoSubastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosNoSubastActionPerformed
        ProductoServices objProductoServices = new ProductoServices();
        List<Producto> lstProductos = objProductoServices.ListarProductos("En espera");
        cargar_tabla4(lstProductos);
    }//GEN-LAST:event_btnProductosNoSubastActionPerformed
    public void cargar_tabla2(List<Producto> lstProductos) {
        Object matriz[][] = new Object[lstProductos.size()][4];

        for (int i = 0; i < lstProductos.size(); i++) {
            matriz[i][0] = lstProductos.get(i).getCodigo();
            matriz[i][1] = lstProductos.get(i).getNombre();
            matriz[i][2] = lstProductos.get(i).getValor_inicial();
            matriz[i][3] = lstProductos.get(i).getEstado();
        }
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                matriz, new String[]{"Código", "Nombre", "Valor inicial", "Estado"}));
    }
    public void cargar_tabla4(List<Producto> lstProductos) {
        Object matriz[][] = new Object[lstProductos.size()][4];

        for (int i = 0; i < lstProductos.size(); i++) {
            matriz[i][0] = lstProductos.get(i).getCodigo();
            matriz[i][1] = lstProductos.get(i).getNombre();
            matriz[i][2] = lstProductos.get(i).getValor_inicial();
            matriz[i][3] = lstProductos.get(i).getEstado();
        }
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                matriz, new String[]{"Código", "Nombre", "Valor inicial", "Estado"}));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProductosNoSubast;
    private javax.swing.JButton btnProductosSubast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
