package view;

/**
 *
 * @author YazminG, ErikaC
 */
public class JDialogMenuAdmin extends javax.swing.JDialog {
    private JPanelRegistrarProducto objPRegistrarProducto;
    private JPanelListarProducto objPListarProducto;
    private JPanelAbrirSubasta objPAbrirSubasta;
    private JPanelCerrarSubasta objCerrarSubasta;

    /**
     * Creates new form JDialogMenuAdmin
     */
    public JDialogMenuAdmin(JDialogInicioSesionAdmin parent, boolean modal) {
        super(parent, modal);
        this.objPRegistrarProducto = new JPanelRegistrarProducto();
        this.objPListarProducto = new JPanelListarProducto();
        this.objPAbrirSubasta = new JPanelAbrirSubasta();
        this.objCerrarSubasta = new JPanelCerrarSubasta();        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelIzq = new javax.swing.JPanel();
        btnRegistrarProducto = new javax.swing.JButton();
        btnListarProductos = new javax.swing.JButton();
        btnCerrarSubasta = new javax.swing.JButton();
        btnAbrirSubasta = new javax.swing.JButton();
        jPanelCentral = new javax.swing.JPanel();
        jPanelSup = new javax.swing.JPanel();
        label1 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnRegistrarProducto.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnRegistrarProducto.setLabel("Registrar producto");
        btnRegistrarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarProductoActionPerformed(evt);
            }
        });

        btnListarProductos.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnListarProductos.setText("Listar Productos");
        btnListarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProductosActionPerformed(evt);
            }
        });

        btnCerrarSubasta.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnCerrarSubasta.setText("Cerrar Subasta");
        btnCerrarSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSubastaActionPerformed(evt);
            }
        });

        btnAbrirSubasta.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        btnAbrirSubasta.setText("Abrir Subasta");
        btnAbrirSubasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirSubastaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelIzqLayout = new javax.swing.GroupLayout(jPanelIzq);
        jPanelIzq.setLayout(jPanelIzqLayout);
        jPanelIzqLayout.setHorizontalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCerrarSubasta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelIzqLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnAbrirSubasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelIzqLayout.setVerticalGroup(
            jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelIzqLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btnRegistrarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(btnCerrarSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
            .addGroup(jPanelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelIzqLayout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addComponent(btnAbrirSubasta, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(213, Short.MAX_VALUE)))
        );

        jPanelCentral.setLayout(new java.awt.BorderLayout());

        label1.setFont(new java.awt.Font("Century Gothic", 1, 19)); // NOI18N
        label1.setText("MENÚ ADMINISTRADOR");

        javax.swing.GroupLayout jPanelSupLayout = new javax.swing.GroupLayout(jPanelSup);
        jPanelSup.setLayout(jPanelSupLayout);
        jPanelSupLayout.setHorizontalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
        jPanelSupLayout.setVerticalGroup(
            jPanelSupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanelSup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarProductoActionPerformed
        registrarProducto();
    }//GEN-LAST:event_btnRegistrarProductoActionPerformed

    private void btnListarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProductosActionPerformed
        listarProductos();
    }//GEN-LAST:event_btnListarProductosActionPerformed

    private void btnAbrirSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirSubastaActionPerformed
        abrirSubasta();
    }//GEN-LAST:event_btnAbrirSubastaActionPerformed

    private void btnCerrarSubastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSubastaActionPerformed
        cerrarSubasta();
    }//GEN-LAST:event_btnCerrarSubastaActionPerformed
    private void registrarProducto(){
        this.jPanelCentral.remove(objPListarProducto);
        this.jPanelCentral.remove(objCerrarSubasta);
        this.jPanelCentral.remove(objPAbrirSubasta);
        this.jPanelCentral.add(objPRegistrarProducto);
        this.jPanelCentral.revalidate();
        this.jPanelCentral.repaint();
    }
    private void listarProductos() {
        this.jPanelCentral.remove(objPRegistrarProducto);
        this.jPanelCentral.remove(objCerrarSubasta);
        this.jPanelCentral.remove(objPAbrirSubasta);
        this.jPanelCentral.add(objPListarProducto);
        this.jPanelCentral.revalidate();
        this.jPanelCentral.repaint();
    }
    private void abrirSubasta() {
        this.jPanelCentral.remove(objPListarProducto);
        this.jPanelCentral.remove(objCerrarSubasta);
        this.jPanelCentral.remove(objPRegistrarProducto);
        this.jPanelCentral.add(objPAbrirSubasta);
        this.jPanelCentral.revalidate();
        this.jPanelCentral.repaint();
    }
    private void cerrarSubasta() {
        this.jPanelCentral.remove(objPListarProducto);
        this.jPanelCentral.remove(objPAbrirSubasta);
        this.jPanelCentral.remove(objPRegistrarProducto);
        this.jPanelCentral.add(objCerrarSubasta);
        this.jPanelCentral.revalidate();
        this.jPanelCentral.repaint();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JDialogMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JDialogMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JDialogMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JDialogMenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                JDialogMenuAdmin dialog = new JDialogMenuAdmin(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirSubasta;
    private javax.swing.JButton btnCerrarSubasta;
    private javax.swing.JButton btnListarProductos;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelIzq;
    private javax.swing.JPanel jPanelSup;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
